### ISSUE TITLE
静态文件嵌入到可执行文件中之后，docker部署就无法自定义index.html文件样式

### ISSUE THREAD

**Issue by ymliusu** [srcrs/rss-reader#11]
docker镜像中/app/index.html文件映射到宿主机之后，修改index.html文件不起作用，因为rss-reader程序调用的是内部的index.html文件。

**Comment by srcrs** [comment]
可以docker build打包自己的镜像的

**Comment by ymliusu** [comment]
打包自己的镜像没问题，但是代码里main.go不是指定读取内嵌的静态文件么？意思代码也改一改，恢复到之前版本的代码？

**Comment by srcrs** [comment]
go代码不需要改动的，embed的作用是在打包时将静态文件嵌入

**Comment by Lyric-c** [comment]
> 打包自己的镜像没问题，但是代码里main.go不是指定读取内嵌的静态文件么？意思代码也改一改，恢复到之前版本的代码？

读取的静态文件是在编译的时候确定的。编译好之后就不会再次读取已经内嵌的静态文件了。

用 docker 部署的话，大体步骤应该是：
1. git clone
2. 修改对应的静态文件
3. docker build
4. docker run

**Comment by ymliusu** [comment]
> > 打包自己的镜像没问题，但是代码里main.go不是指定读取内嵌的静态文件么？意思代码也改一改，恢复到之前版本的代码？
> 
> 读取的静态文件是在编译的时候确定的。编译好之后就不会再次读取已经内嵌的静态文件了。
> 
> 用 docker 部署的话，大体步骤应该是：
> 
> 1. git clone
> 2. 修改对应的静态文件
> 3. docker build
> 4. docker run

那这样的话，docker部署以后就不能随时随地修改index.html了，修改必须重新打镜像，重新部署，是吧？
