### ISSUE TITLE
能支持在ARM架构的服务器上执行吗？

### ISSUE THREAD

**Issue by myhfw003** [srcrs/rss-reader#18]
不太确定是不是ARM服务器的原因，但报exec ./rss-reader: exec format error这个错误，排查了执行权限、端口号冲突的，都没有发现问题，所以来请教下

**Comment by srcrs** [comment]
之前是没有打包arm镜像，刚刚已经加上了，再试试？

**Comment by myhfw003** [comment]
可以了，哈哈，多谢！
