### ISSUE TITLE
部署容器后，这个首页文件在容器那里，好像都找不出来。/globals/static /index.html

### ISSUE THREAD

**Issue by kasfori** [srcrs/rss-reader#21]
我想修改下页面字体和样式。但是在部署后的容器中找不到   index.html，

**Comment by srcrs** [comment]
> 我想修改下页面字体和样式。但是在部署后的容器中找不到 index.html，

页面是嵌入到代码中的，更改完之后需要重新打包镜像

**Comment by kasfori** [comment]
> > 我想修改下页面字体和样式。但是在部署后的容器中找不到 index.html，
> 
> 页面是嵌入到代码中的，更改完之后需要重新打包镜像

能否介绍下具体怎么修改吗？

**Comment by srcrs** [comment]
> > > 我想修改下页面字体和样式。但是在部署后的容器中找不到 index.html，
> > 
> > 
> > 页面是嵌入到代码中的，更改完之后需要重新打包镜像
> 
> 能否介绍下具体怎么修改吗？

1.拷贝项目后，直接修改/globals/static/index.html 文件
2.修改完成后，重新打包镜像 docker build -t srcrs/rss-reader:latest .
3.重新启动项目即可 docker compose down | docker compose up -d

**Comment by srcrs** [comment]
如果还不行的话，您可以通过主页邮件地址发一下微信号

**Comment by kasfori** [comment]
> 如果还不行的话，您可以通过主页邮件地址发一下微信号

好的，感谢，我试一试！
