### ISSUE TITLE
LowEndTalk的rss在哪里？？

### ISSUE THREAD

**Issue by openMJJ** [srcrs/rss-reader#22]
LowEndTalk的rss在哪里？？
老板求教。

**Comment by srcrs** [comment]
> LowEndTalk的rss在哪里？？ 老板求教。

这是其中一个
https://lowendtalk.com/discussions/feed.rss

还可以订阅分类下的rss，可以找一下关注的
https://lowendtalk.com/categories

**Comment by openMJJ** [comment]
> > LowEndTalk的rss在哪里？？ 老板求教。
> 
> 
> 
> 这是其中一个
> 
> https://lowendtalk.com/discussions/feed.rss
> 
> 
> 
> 还可以订阅分类下的rss，可以找一下关注的
> 
> https://lowendtalk.com/categories

谢谢佬
