### ISSUE TITLE
订阅地址太长的话，前面大部分相同，界面只显示最后一个

### ISSUE THREAD

**Issue by worldyouwyl** [srcrs/rss-reader#23]
完整的显示，就在刷新好的一瞬间，后面就消失了

**Comment by srcrs** [comment]
> 完整的显示，就在刷新好的一瞬间，后面就消失了

方便录个屏吗

**Comment by worldyouwyl** [comment]
几个前面部分相同的订阅地址，
只显示最后一个订阅地址。

**Comment by worldyouwyl** [comment]
录频传不上去

**Comment by worldyouwyl** [comment]
https://github.com/srcrs/rss-reader/assets/18330306/e0fc432a-f275-4815-882f-a085b6b5d3aa

**Comment by srcrs** [comment]
大概已经知道原因了，提供下可以复现的订阅地址，下个版本修复一下。

**Comment by worldyouwyl** [comment]
> 大概已经知道原因了，提供下可以复现的订阅地址，下个版本修复一下。

已发邮件

**Comment by srcrs** [comment]
问题已在v2.1版本修复，拉取最新版本镜像可解决
