### ISSUE TITLE
优化文本溢出情况

### ISSUE THREAD

**Issue by Gnoloah** [srcrs/rss-reader#7]
大佬能不能优化下RSS条目标题的文本框，根据文本多少改变文本框高度，就像今日热榜那样的可以多行显示不截断

**Comment by liangweipeng** [comment]
我改了点样式，可以试一下。大佬这项目现在是我的主力阅读器了

**Comment by srcrs** [comment]
> 大佬能不能优化下RSS条目标题的文本框，根据文本多少改变文本框高度，就像今日热榜那样的可以多行显示不截断

已经改成多行了
