### ISSUE TITLE
一段时间后，就不刷新了

### ISSUE THREAD

**Issue by jmmes** [srcrs/rss-reader#9]
有些rss源更新太慢了！

**Comment by dalaolala** [comment]
确实有这个问题  貌似是websocket断开了

**Comment by srcrs** [comment]
> 确实有这个问题 貌似是websocket断开了

对的，这里看后面怎么优化下

**Comment by srcrs** [comment]
删除了websocket心跳，前端检测到断开，自动重新连接

**Comment by srcrs** [comment]
接下来，计划在前端加入心跳逻辑，减少自动重连的概率
